### ISSUE TITLE
ability to mark release as a pre-release

### ISSUE THREAD

**Issue by davelandry** [coderaiser/node-grizzly#2]

**Comment by coderaiser** [comment]
What do you mean by `pre-release`? Is it specific prefix for tags?

**Comment by davelandry** [comment]
For example, I have been marking the < 1.0 releases of my repositories as "pre-release": https://github.com/d3plus/d3plus-text/releases. You see it as a checkbox when creating release notes through the web interface.

Looks like it's part of the createRelease payload as a Boolean: https://developer.github.com/v3/repos/releases/#create-a-release

I feel pretty comfortable creating a pull request, would it just be as simple as passing another argument here? https://github.com/coderaiser/node-grizzly/blob/master/lib/release.js#L45

Was thinking:

``` js
prerelease: options.prerelease || false,
```

**Comment by coderaiser** [comment]
Yes, it would be great. Place you mentioned is right one, but there is a few more:
[bin](https://github.com/coderaiser/node-grizzly/blob/master/bin/release.js#L12-L49) and [global part of docs](https://github.com/coderaiser/node-grizzly/blob/master/README.md#global), and [example part of docs](https://github.com/coderaiser/node-grizzly/blob/master/README.md#example).

**Comment by coderaiser** [comment]
@davelandry any progress with this?

**Comment by davelandry** [comment]
I haven't had a chance to do this yet, and probably won't until next week at the earliest.

**Comment by davelandry** [comment]
@coderaiser nevermind, I'm going to do this right now. get ready for the pull request!
