### ISSUE TITLE
ability to upload a binary file with a release

### ISSUE THREAD

**Issue by davelandry** [coderaiser/node-grizzly#3]

**Comment by coderaiser** [comment]
Good idea, I'll think about. Maybe you know some `npm` modules that can help with this feature? Pull requests are welcome.

**Comment by davelandry** [comment]
I found this project that claims to do it: https://github.com/bartinger/grunt-github-release-asset

Looks like they use a separate `uploadAsset` Github task: https://github.com/Bartinger/grunt-github-release-asset/blob/master/tasks/github_release_asset.js#L86

Here's the Github docs for it: https://developer.github.com/v3/repos/releases/#upload-a-release-asset

It's a little outside of my knowledge area, but I wouldn't mind tinkering if I find the time. Just let me know if you start working on it so we're not stepping on each others toes.

**Comment by davelandry** [comment]
Oh, and sorry I forgot to mention, great work on this library! 😄

**Comment by coderaiser** [comment]
Could be solved with help of [putasset](https://github.com/coderaiser/node-putasset).

**Comment by davelandry** [comment]
Smart separating this out to it's own library. Thanks so much! Will start using it ASAP.
