### ISSUE TITLE
unable to create release for ORG specific repos

### ISSUE THREAD

**Issue by gs-nvulli** [coderaiser/node-grizzly#7]
Hi can you please let me know if we can create release  for org specific releases.

getting below error while trying for the same.
please help.

########ERROR MESSAGE ##########
(node:15176) UnhandledPromiseRejectionWarning: HttpError: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/releases/#create-a-release"}
    at IncomingMessage.<anonymous> (/Users/nvulli/workspace/node_modules/@octokit/rest/lib/request/request.js:73:18)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
(node:15176) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15176) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

thanks,
Nitish

**Comment by coderaiser** [comment]
What do you mean by org specific releases? `grizzly` works with releases for github repos.

What parameters do you pass?

**Comment by gs-nvulli** [comment]
hi @coderaiser ,

Thanks for responding.
org specific means github private/enterprise  repos will have repo urls in below format.
https://github.com/Orgname/reponame

so i need to specify  org name in input parameters??

thanks,
Nitish

**Comment by coderaiser** [comment]
@gs-nvulli that's right, `orgname` will be `user`

```
  -u, --user                  user of repository
```

is it helped?

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝
